application: raytracegame
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /scripts
  static_dir: scripts

- url: /static
  static_dir: static

- url: /places
  static_dir: places

- url: /.*
  script: raytracegame.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest
