application: raytracegame
version: 1
runtime: go
api_version: go1

handlers:
- url: /places
  static_dir: places
- url: /masks
  static_dir: masks
- url: /js
  mime_type: text/javascript
  static_dir: js
- url: /static
  static_dir: static
- url: /.*
  script: _go_app

